### =========================
### ORDER SERVICE - SYNC
### =========================
POST http://localhost:5265/api/orders/sync
Content-Type: application/json

{
  "productId": "11111111-1111-1111-1111-111111111111",
  "quantity": 2
}


### =========================
### ORDER SERVICE - ASYNC	InventoryFailed
### =========================
POST http://localhost:5265/api/orders/async
Content-Type: application/json

{
  "productId": "11111111-1111-1111-1111-111111111111",
  "quantity": 2
}


### =========================
### ORDER SERVICE - ASYNC Completed
### =========================
POST http://localhost:5265/api/orders/async
Content-Type: application/json

{
  "productId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "quantity": 2
}

### =========================
### ORDER SERVICE - BENCHMARK
### =========================
GET http://localhost:5265/api/benchmark/data-transfer/10
