global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:8080'] 

  - job_name: 'inventory-service'
    static_configs:
      - targets: ['inventory-service:5002']

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:5004']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
